# Generated by Django 4.2 on 2024-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custombaseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
