# Generated by Django 4.2 on 2024-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custombaseuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='data_joined',
            field=models.DateTimeField(auto_created=True, default=None),
        ),
    ]
