# Generated by Django 4.2 on 2024-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custombaseuser_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='data_joined',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
