# Generated by Django 5.1.3 on 2024-11-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custombaseuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='confirm_password',
            field=models.IntegerField(),
        ),
    ]
