# Generated by Django 5.1.3 on 2024-11-19 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_confirm_password_custombaseuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombaseuser',
            name='password2',
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
