# Generated by Django 4.2 on 2024-12-16 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_custombaseuser_data_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='data_joined',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
