# Generated by Django 5.1.3 on 2024-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_custombaseuser_password2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
