# Generated by Django 4.2 on 2024-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_custombaseuser_data_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='There is no description', max_length=700),
        ),
    ]
