# Generated by Django 5.1.3 on 2024-11-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_custombaseuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='site_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
