# Generated by Django 4.2 on 2024-12-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_create_products', 'Can create products')]},
        ),
    ]
