# Generated by Django 5.1.3 on 2024-12-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_address_alter_orders_discount_amount'),
        ('product', '0005_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.productsize'),
        ),
    ]
