# Generated by Django 5.1.3 on 2024-12-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='age',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='account_password',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='order_notes',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
