# Generated by Django 5.1.3 on 2024-12-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_billingdetails_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='account_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='order_notes',
            field=models.CharField(max_length=500),
        ),
    ]
