# Generated by Django 5.1.3 on 2024-12-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_billingdetails_account_password_and_more'),
        ('product', '0008_product_num_of_times_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.productsize'),
        ),
    ]
