# Generated by Django 4.2 on 2024-12-17 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitems_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
