# Generated by Django 4.2 on 2024-12-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
