# Generated by Django 5.1.3 on 2024-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_populate_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_products', 'Can create products')]},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('LV', 'Louis Vuitton'), ('Hermes', 'Hermes'), ('Gucci', 'Gucci'), ('Chanel', 'Chanel')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('pink', 'Pink'), ('light-purple', 'Light-Purple'), ('grey', 'Grey'), ('brown', 'Brown')]),
        ),
    ]
