# Generated by Django 5.1.3 on 2024-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='max_size',
            field=models.CharField(blank=True, null=True),
        ),
    ]
