# Generated by Django 5.1.3 on 2024-11-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can _create_products', 'Can create posts')]},
        ),
    ]
