# Generated by Django 5.1.3 on 2024-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productsize_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='max_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
