# Generated by Django 5.1.3 on 2024-11-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_products', 'Can create posts')]},
        ),
    ]
