# Generated by Django 5.1.3 on 2024-12-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productsize_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_times_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
