# Generated by Django 5.1.3 on 2024-12-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_max_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_price',
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('max_quantity_accessory', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory', to='product.product')),
            ],
        ),
    ]
