# Generated by Django 5.1.3 on 2024-12-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_max_price_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='id',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accessory', serialize=False, to='product.product'),
        ),
    ]
