# Generated by Django 4.2 on 2024-12-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
