# Generated by Django 4.2 on 2024-12-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_products', 'Can create products')]},
        ),
    ]
