# Generated by Django 4.2 on 2024-12-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
